#!/bin/sh
unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS
export XKL_XMODMAP_DISABLE=1

# Start dbus
if [ -x /usr/bin/dbus-launch ]; then
    eval `dbus-launch --sh-syntax --exit-with-session`
fi

# Start GNOME Desktop
exec /usr/bin/gnome-session
